name: lask_mobile_news_app
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  # internationalization & localization
  intl: ^0.19.0
  # state management
  flutter_bloc: ^8.1.5
  # persistent storage
  hydrated_bloc: ^9.1.5
  shared_preferences: ^2.2.3
  equatable: ^2.0.5
  path_provider: ^2.1.3
  # networking
  http: ^1.2.1
  # routing & navigation
  go_router: ^14.0.2
  google_nav_bar: ^5.0.6
  # images
  cached_network_image: ^3.3.1
  flutter_svg: ^2.0.10+1
  # icons
  flutter_material_symbols: ^0.0.4
  cupertino_icons: ^1.0.6
  # components
  webview_flutter: ^4.7.0
  # transitions & animations
  scroll_to_hide: ^2.1.0
  shimmer: ^3.0.0
  lottie: ^3.1.0
  # alerts & dialogs
  delightful_toast: ^1.1.0
  giffy_dialog: ^2.1.0
  # sharing & url launcher
  share_plus: any
  url_launcher: ^6.2.6
  # app icon & splash screen
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
    - assets/fonts/
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/inter/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/inter/Inter-Regular.ttf
          weight: 400
    - family: SchibstedGrotesk
      fonts:
        - asset: assets/fonts/schibstedGrotesk/SchibstedGrotesk-Regular.ttf
          weight: 400
    - family: Merriweather
      fonts:
        - asset: assets/fonts/merriweather/Merriweather-Regular.ttf
          weight: 400

flutter_native_splash:
  color: "#E9EEFA"
  color_dark: "#1A1A1A"
  image: assets/icons/splash_screen_icon.png
  android_12:
    image: assets/icons/splash_screen_icon.png

flutter_launcher_icons:
  android: "launcher_icon"
  ios: "AppIcon"
  image_path: "assets/icons/app_icon.png"
  min_sdk_android: 21
  remove_alpha_ios: true
